export const DOCTOR_SPECIALTIES = [
  "General Surgery",
  "Neurosurgery",
  "Cardiothoracic Surgery",
  "Vascular Surgery",
  "GI Surgery",
  "Urology",
  "Surgical Oncology",
  "Paediatric Surgery",
  "Plastic & Reconstructive Surgery",
  "Trauma Surgery",
  "Orthopaedic",
  "Obstetrics & Gynaecology",
  "Pediatrics",
  "Orthopaedics",
  "Dermatology",
  "Psychiatry",
  "Ophthalmology",
  "ENT",
  "Dentistry",
  "Rural Medical Practitioner",
  "Homeopathy",
  "Ayurveda",
  "General Medicine",
  "Cardiology",
  "Neurology",
  "Nephrology",
  "Gastroenterology",
  "Pulmonology / Chest Medicine",
  "Endocrinology",
  "Rheumatology",
  "Haematology",
  "Medical Oncology",
  "Infectious Disease",
  "ECG",
  "EEG",
  "ECHO",
  "RADIOLOGY - X-RAY, USG, CT SCAN, MRI",
  "PATHOLOGY",
  "NCV (Nerve Conduction System)",
  "PHYSIOTHERAPY",
  "Animal Doctor",
];
